vim.opt.guicursor = ""
vim.opt.nu = true
vim.opt.relativenumber = true

vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.smartindent = true
vim.opt.wrap = true
vim.opt.laststatus=2
vim.opt.foldlevel=99
vim.opt.tabstop=4
vim.opt.shiftwidth=4
vim.opt.title = true
vim.g.mapleader = " "
vim.g.rustfmt_autosave = 1
